FROM node:16

# ADD . /app/oppia
WORKDIR /app

RUN echo 'deb http://ftp.debian.org/debian stretch-backports main' | tee /etc/apt/sources.list.d/stretch-backports.list

RUN apt-get update
RUN apt-get install -y openjdk-11-jre-headless
RUN apt-get clean

RUN npm i -g firebase-tools

EXPOSE 9099