version: "3.4"

services:
  webserver: 
    build: .
    ports:
      - "4200:4200"
    volumes: 
      - .:/app/oppia
    environment:
      - NODE_ENV=development
    depends_on:
      - redis

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - .:/app/firebase_emulator_cache
