name: Docker Setup Test

on: [push]

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Containers
        run: docker compose -f "docker-compose.yml" up -d --build
