name: Docker Setup Test

on: [push]

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Containers
        run: | 
          echo ---Building and starting up docker---
          docker-compose -f docker-compose.yml up -d
          echo ---Containers up---

      - name: Checking dev-server reachability
        run: |
          curl localhost:8181
          echo ---Dev-Server is up properly---
        
      - name: Stop Containers
        run: docker compose down
