name: End-to-End tests
on:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - develop
      - release-*
  pull_request:
    branches:
      - develop
      - release-*

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - name: Install dependencies 
      # necessary dependencies (redis, App Engine, npm libraries, etc.)
        run: make install-dependencies
      - name: Install and updates the pip and npm packages
      # locally install packages with version specified
        run: make update-pip-and-npm-packages

  e2e_test:
    needs: build
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        suite:
          - accessibility
          - additionalEditorFeatures
          - additionalEditorFeaturesModals
          - additionalPlayerFeatures
          - adminPage
          - blogDashboard
          - blog
          - checkpointFeatures
          - classroomPage
          - classroomPageFileUploadFeatures
          - collections
          - contributorDashboard
          - coreEditorAndPlayerFeatures
          - creatorDashboard
          - embedding
          - explorationFeedbackTab
          - explorationImprovementsTab
          - explorationHistoryTab
          - explorationStatisticsTab
          - explorationTranslationTab
          - extensions
          - featureGating
          - fileUploadExtensions
          - fileUploadFeatures
          - learner
          - learnerDashboard
          - library
          - navigation
          - playVoiceovers
          - preferences
          - profileFeatures
          - profileMenu
          - publication
          - skillEditor
          - subscriptions
          - topicsAndSkillsDashboard
          - topicAndStoryEditor
          - topicAndStoryEditorFileUploadFeatures
          - topicAndStoryViewer
          - users
          - wipeout
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8.15'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            requirements.in
            requirements.txt
            requirements_dev.in
            requirements_dev.txt
      - uses: ./.github/actions/merge
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: /home/runner/work/oppia/yarn_cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Download build files artifact
        uses: actions/download-artifact@v3
        with:
          name: build_files
          path: /home/runner/work/oppia/
      - name: Unzip build files
        run: |
          ls -la
          unzip build_files.zip
          rm build_files.zip
          echo "Files in ./:"
          ls -la .
          echo "Files in oppia_tools:"
          ls -la oppia_tools
          echo "Files in oppia:"
          ls -la oppia
          echo "Files in build:"
          ls -la oppia/build
          echo "Files in third_party:"
          ls -la oppia/third_party
        working-directory: /home/runner/work/oppia
        shell: bash
      - uses: ./.github/actions/install-oppia-dependencies
      - name: Install chrome
        run: python -m scripts.install_chrome_for_ci
      - name: Install ffmpeg
        run: sudo apt install ffmpeg
      - name: Run E2E Test ${{ matrix.suite }}
        run: xvfb-run -a --server-args="-screen 0, 1285x1000x24" python -m scripts.run_e2e_tests --skip-install --skip-build --suite=${{ matrix.suite }} --prod_env
        env:
          VIDEO_RECORDING_IS_ENABLED: 0
      - name: Uploading webdriverio-video as Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: webdriverio-video
          path: /home/runner/work/oppia/webdriverio-video
      - name: Uploading webdriverio screenshots as Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: webdriverio-screenshots
          path: /home/runner/work/oppia/webdriverio-screenshots
      - name: Uploading webpack bundles as an artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: webpack-bundles
          path: /home/runner/work/oppia/oppia/build
      - name: Report failure if failed on oppia/oppia develop branch
        if: ${{ failure() && github.event_name == 'push' && github.repository == 'oppia/oppia' && github.ref == 'refs/heads/develop'}}
        uses: ./.github/actions/send-webhook-notification
        with:
          message: "An E2E test failed on the upstream develop branch."
          webhook-url: ${{ secrets.BUILD_FAILURE_ROOM_WEBHOOK_URL }}
